project:
  type: book
  output-dir: _book

book:
  title: "End To End Data Science With R"
  author: "Rene Essomba"
  reader-mode: true
  search: true
  page-footer:
    left: |
      End to End Data Science with R was written by Rene Essomba.
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  cover-image: cover_new.png
  favicon: cover.png
  site-url: https://e2e-ds-r.franckess.com
  repo-url: https://www.github.com/franckess/QMD_E2E_DataScience_R
  repo-branch: main
  repo-actions: [edit, issue]
  sharing: [twitter, facebook, linkedin]
  chapters:
    - index.qmd
    - intro.qmd
    - part: introduction.qmd
      chapters: 
        - understanding-ds.qmd
        - understanding-r-applications.qmd
        - r-objects-and-variables.qmd
    - part: data-exploration-vis.qmd
      chapters: 
        - basic-stats-r.qmd
        - data-manipulation.qmd
        - feature-eng.qmd
        - handling-data-issues.qmd
        - data-visualisation.qmd
    - part: supervised-learning.qmd
      chapters: 
        - basic-supervised-learning.qmd
        - linear-reg.qmd
        - k-nearest-neighbour-reg.qmd
        - class-log-reg.qmd
    - part: unsupervised-learn.qmd
      chapters: 
        - basic-unsupervised-learning.qmd
        - k-means-clust.qmd
        - hier-clust.qmd
        - pca.qmd
        - t-sne.qmd
    - part: other-topic-ds.qmd
      chapters: 
        - time-series.qmd
        - svm.qmd
        - semi-sup.qmd
        - basics-nn.qmd
    - part: nlp.qmd
      chapters: 
        - basics-nlp.qmd
        - understanding-nlp.qmd
        - apply-nlp.qmd
    - part: img-proc.qmd
      chapters: 
        - intro-img-proc.qmd
        - img-seg.qmd
#    - part: rl.qmd
#      chapters: 
#        - basics-rl.qmd
#        - markov-dec-proc.qmd
#        - apply-rl.qmd
    #- summary.qmd
    #- references.qmd

#bibliography: references.bib

format:
  html:
    theme: 
      - cosmo
      - styling.scss
    code-link: true
    author-meta: "Rene Essomba"
    include-in-header: plausible.html
    callout-appearance: simple
    light: flatly
    dark: darkly
  #pdf:
   # documentclass: scrreprt

editor: visual
